from flask import render_template, request, redirect
from models.home import all_sheets, get_sheets, create_sheets, update_sheet, delete_sheet
from services.session_info import current_user

def index():
    sheets = all_sheets()
    return render_template ('home/index.html', sheets=sheets, current_user=current_user)

def new():
    return render_template('home/create.html')

def create():
    character_name = request.form.get('character_name')
    class_and_level = request.form.get('class_and_level')
    background = request.form.get('background')
    player_name = request.form.get('player_name')
    race = request.form.get('race')
    alignment = request.form.get('alignment')
    experience_points = request.form.get('experience_points')
    stat_str = request.form.get('stat_str')
    stat_dex = request.form.get('stat_dex')
    stat_con = request.form.get('stat_con')
    stat_int = request.form.get('stat_int')
    stat_wis = request.form.get('stat_wis')
    stat_cha = request.form.get('stat_cha')
    passive_perception = request.form.get('passive_perception')
    svgthrow_stat_str = request.form.get('svgthrow_stat_str')
    svgthrow_stat_dex = request.form.get('svgthrow_stat_dex')
    svgthrow_stat_con = request.form.get('svgthrow_stat_con')
    svgthrow_stat_int = request.form.get('svgthrow_stat_int')
    svgthrow_stat_wis = request.form.get('svgthrow_stat_wis')
    svgthrow_stat_cha = request.form.get('svgthrow_stat_cha')
    sk_acroba = request.form.get('sk_acroba')
    sk_animal = request.form.get('sk_animal')
    sk_arcana = request.form.get('sk_arcana')
    sk_athlet = request.form.get('sk_athlet')
    sk_decept = request.form.get('sk_decept')
    sk_histor = request.form.get('sk_histor')
    sk_insigh = request.form.get('sk_insigh')
    sk_intimi = request.form.get('sk_intimi')
    sk_invest = request.form.get('sk_invest')
    sk_medici = request.form.get('sk_medici')
    sk_nature = request.form.get('sk_nature')
    sk_percep = request.form.get('sk_percep')
    sk_perfor = request.form.get('sk_perfor')
    sk_persua = request.form.get('sk_persua')
    sk_religi = request.form.get('sk_religi')
    sk_sleigh = request.form.get('sk_sleigh')
    sk_stealt = request.form.get('sk_stealt')
    sk_suviva = request.form.get('sk_suviva')
    otr_prof_lang = request.form.get('otr_prof_lang')
    armor = request.form.get('armor')
    initiative = request.form.get('initiative')
    speed = request.form.get('speed')
    current_hp = request.form.get('current_hp')
    temp_hp = request.form.get('temp_hp')
    hit_dice = request.form.get('hit_dice')
    dthsv_pass = request.form.get('dthsv_pass')
    dthsv_fail = request.form.get('dthsv_fail')
    attacks_spells = request.form.get('attacks_spells')
    equipment = request.form.get('equipment')
    traits = request.form.get('traits')
    ideals = request.form.get('ideals')
    bonds = request.form.get('bonds')
    flaws = request.form.get('flaws')
    fluff = request.form.get('fluff')
    create_sheets(character_name, class_and_level, background, player_name, race, alignment, experience_points, stat_str, stat_dex, stat_con, stat_int, stat_wis, stat_cha, passive_perception, svgthrow_stat_str, svgthrow_stat_dex, svgthrow_stat_con, svgthrow_stat_int, svgthrow_stat_wis, svgthrow_stat_cha, sk_acroba, sk_animal, sk_arcana, sk_athlet, sk_decept, sk_histor, sk_insigh, sk_intimi, sk_invest, sk_medici, sk_nature, sk_percep, sk_perfor, sk_persua, sk_religi, sk_sleigh, sk_stealt, sk_suviva, otr_prof_lang, armor, initiative, speed, current_hp, temp_hp, hit_dice, dthsv_pass, dthsv_fail, attacks_spells, equipment, traits, ideals, bonds, flaws, fluff)
    return redirect('/')

def edit(id):
  sheet = get_sheets(id)
  return render_template('home/edit.html', sheet=sheet)

def update(id):
    character_name = request.form.get('character_name')
    class_and_level = request.form.get('class_and_level')
    background = request.form.get('background')
    player_name = request.form.get('player_name')
    race = request.form.get('race')
    alignment = request.form.get('alignment')
    experience_points = request.form.get('experience_points')
    stat_str = request.form.get('stat_str')
    stat_dex = request.form.get('stat_dex')
    stat_con = request.form.get('stat_con')
    stat_int = request.form.get('stat_int')
    stat_wis = request.form.get('stat_wis')
    stat_cha = request.form.get('stat_cha')
    passive_perception = request.form.get('passive_perception')
    svgthrow_stat_str = request.form.get('svgthrow_stat_str')
    svgthrow_stat_dex = request.form.get('svgthrow_stat_dex')
    svgthrow_stat_con = request.form.get('svgthrow_stat_con')
    svgthrow_stat_int = request.form.get('svgthrow_stat_int')
    svgthrow_stat_wis = request.form.get('svgthrow_stat_wis')
    svgthrow_stat_cha = request.form.get('svgthrow_stat_cha')
    sk_acroba = request.form.get('sk_acroba')
    sk_animal = request.form.get('sk_animal')
    sk_arcana = request.form.get('sk_arcana')
    sk_athlet = request.form.get('sk_athlet')
    sk_decept = request.form.get('sk_decept')
    sk_histor = request.form.get('sk_histor')
    sk_insigh = request.form.get('sk_insigh')
    sk_intimi = request.form.get('sk_intimi')
    sk_invest = request.form.get('sk_invest')
    sk_medici = request.form.get('sk_medici')
    sk_nature = request.form.get('sk_nature')
    sk_percep = request.form.get('sk_percep')
    sk_perfor = request.form.get('sk_perfor')
    sk_persua = request.form.get('sk_persua')
    sk_religi = request.form.get('sk_religi')
    sk_sleigh = request.form.get('sk_sleigh')
    sk_stealt = request.form.get('sk_stealt')
    sk_suviva = request.form.get('sk_suviva')
    otr_prof_lang = request.form.get('otr_prof_lang')
    armor = request.form.get('armor')
    initiative = request.form.get('initiative')
    speed = request.form.get('speed')
    current_hp = request.form.get('current_hp')
    temp_hp = request.form.get('temp_hp')
    hit_dice = request.form.get('hit_dice')
    dthsv_pass = request.form.get('dthsv_pass')
    dthsv_fail = request.form.get('dthsv_fail')
    attacks_spells = request.form.get('attacks_spells')
    equipment = request.form.get('equipment')
    traits = request.form.get('traits')
    ideals = request.form.get('ideals')
    bonds = request.form.get('bonds')
    flaws = request.form.get('flaws')
    fluff = request.form.get('fluff')
    update_sheet(id, character_name, class_and_level, background, player_name, race, alignment, experience_points, stat_str, stat_dex, stat_con, stat_int, stat_wis, stat_cha, passive_perception, svgthrow_stat_str, svgthrow_stat_dex, svgthrow_stat_con, svgthrow_stat_int, svgthrow_stat_wis, svgthrow_stat_cha, sk_acroba, sk_animal, sk_arcana, sk_athlet, sk_decept, sk_histor, sk_insigh, sk_intimi, sk_invest, sk_medici, sk_nature, sk_percep, sk_perfor, sk_persua, sk_religi, sk_sleigh, sk_stealt, sk_suviva, otr_prof_lang, armor, initiative, speed, current_hp, temp_hp, hit_dice, dthsv_pass, dthsv_fail, attacks_spells, equipment, traits, ideals, bonds, flaws, fluff)
    return redirect('/')

def delete(id):
  delete_sheet(id)
  return redirect('/')