CREATE DATABASE dnd_app_db;
\c dnd_app_db

-- Break this into different tables me thinks || At least that's everything from the first page of a character sheet!
CREATE TABLE sheets (
    id SERIAL PRIMARY KEY,
    character_name TEXT,
    class_and_level TEXT,
    background TEXT,
    player_name TEXT,
    race TEXT,
    alignment TEXT,
    experience_points TEXT,
    stat_str TEXT,
    stat_dex TEXT,
    stat_con TEXT,
    stat_int TEXT,
    stat_wis TEXT,
    stat_cha TEXT,
    passive_perception TEXT,
    svgthrow_stat_str TEXT,
    svgthrow_stat_dex TEXT,
    svgthrow_stat_con TEXT,
    svgthrow_stat_int TEXT,
    svgthrow_stat_wis TEXT,
    svgthrow_stat_cha TEXT,
    sk_acroba TEXT,
    sk_animal TEXT,
    sk_arcana TEXT,
    sk_athlet TEXT,
    sk_decept TEXT,
    sk_histor TEXT,
    sk_insigh TEXT,
    sk_intimi TEXT,
    sk_invest TEXT,
    sk_medici TEXT,
    sk_nature TEXT,
    sk_percep TEXT,
    sk_perfor TEXT,
    sk_persua TEXT,
    sk_religi TEXT,
    sk_sleigh TEXT,
    sk_stealt TEXT,
    sk_suviva TEXT,
    otr_prof_lang TEXT,
    armor TEXT,
    initiative TEXT,
    speed TEXT,
    current_hp TEXT,
    temp_hp TEXT,
    hit_dice TEXT,
    dthsv_pass TEXT,
    dthsv_fail TEXT,
    attacks_spells TEXT,
    equipment TEXT,
    traits TEXT,
    ideals TEXT,
    bonds TEXT,
    flaws TEXT,
    fluff TEXT
);

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  password_digest TEXT
);

INSERT INTO sheets(
    character_name,
    class_and_level,
    background,
    player_name,
    race,
    alignment,
    experience_points,
    stat_str,
    stat_dex,
    stat_con,
    stat_int,
    stat_wis,
    stat_cha,
    passive_perception,
    svgthrow_stat_str,
    svgthrow_stat_dex,
    svgthrow_stat_con,
    svgthrow_stat_int,
    svgthrow_stat_wis,
    svgthrow_stat_cha,
    sk_acroba,
    sk_animal,
    sk_arcana,
    sk_athlet,
    sk_decept,
    sk_histor,
    sk_insigh,
    sk_intimi,
    sk_invest,
    sk_medici,
    sk_nature,
    sk_percep,
    sk_perfor,
    sk_persua,
    sk_religi,
    sk_sleigh,
    sk_stealt,
    sk_suviva,
    otr_prof_lang,
    armor,
    initiative,
    speed,
    current_hp,
    temp_hp,
    hit_dice,
    dthsv_pass,
    dthsv_fail,
    attacks_spells,
    equipment,
    traits,
    ideals,
    bonds,
    flaws,
    fluff
    )
VALUES
('test','test','test','test','test','test','test','test','test','test',
'test','test','test','test','test','test','test','test','test','test',
'test','test','test','test','test','test','test','test','test','test',
'test','test','test','test','test','test','test','test','test','test',
'test','test','test','test','test','test','test','test','test','test',
'test', 'test','test','test');

-- 54 values total.